-- 코드를 입력하세요
-- SELECT I.NAME, I.DATETIME
-- FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE O.ANIMAL_ID IS NULL 
-- ORDER BY I.DATETIME
-- FETCH NEXT 3 ROWS ONLY

SELECT i.NAME,i.DATETIME from ANIMAL_INS i left join ANIMAL_OUTS o 
on i.ANIMAL_ID = o.ANIMAL_ID
where o.ANIMAL_ID is null
order by i.DATETIME
fetch first 3 rows only;