SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, round(AVG(NVL(r.REVIEW_SCORE,0)),2) score
FROM REST_INFO i INNER JOIN REST_REVIEW r ON i.rest_id = r.rest_id
WHERE i.address LIKE '서울%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY score DESC, i.FAVORITES DESC;
